/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapeTownRouteImport } from './routes/cape-town'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MatchRouteImport } from './routes/match'
import { Route as PaceRouteImport } from './routes/pace'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TicketRouteImport } from './routes/ticket'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapeTownRoute = CapeTownRouteImport.update({
  id: '/cape-town',
  path: '/cape-town',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const PaceRoute = PaceRouteImport.update({
  id: '/pace',
  path: '/pace',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cape-town': typeof CapeTownRoute
  '/inbox': typeof InboxRoute
  '/match': typeof MatchRoute
  '/pace': typeof PaceRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/ticket': typeof TicketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cape-town': typeof CapeTownRoute
  '/inbox': typeof InboxRoute
  '/match': typeof MatchRoute
  '/pace': typeof PaceRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/ticket': typeof TicketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cape-town': typeof CapeTownRoute
  '/inbox': typeof InboxRoute
  '/match': typeof MatchRoute
  '/pace': typeof PaceRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/ticket': typeof TicketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cape-town'
    | '/inbox'
    | '/match'
    | '/pace'
    | '/pending'
    | '/register'
    | '/ticket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cape-town'
    | '/inbox'
    | '/match'
    | '/pace'
    | '/pending'
    | '/register'
    | '/ticket'
  id:
    | '__root__'
    | '/'
    | '/cape-town'
    | '/inbox'
    | '/match'
    | '/pace'
    | '/pending'
    | '/register'
    | '/ticket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapeTownRoute: typeof CapeTownRoute
  InboxRoute: typeof InboxRoute
  MatchRoute: typeof MatchRoute
  PaceRoute: typeof PaceRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  TicketRoute: typeof TicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cape-town': {
      id: '/cape-town'
      path: '/cape-town'
      fullPath: '/cape-town'
      preLoaderRoute: typeof CapeTownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pace': {
      id: '/pace'
      path: '/pace'
      fullPath: '/pace'
      preLoaderRoute: typeof PaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapeTownRoute: CapeTownRoute,
  InboxRoute: InboxRoute,
  MatchRoute: MatchRoute,
  PaceRoute: PaceRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  TicketRoute: TicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
